name: shiplight-runner
description: Use This GitHub Action to run tests on https://app.shiplight.ai
author: Shiplight AI

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'cloud-lightning'
  color: 'blue'

# Define your inputs here.
inputs:
  api-token:
    description: api token for shiplight
    required: true
  test-suite-id:
    description:
      test suite ID (single ID or comma-separated list, e.g., "suite1" or
      "suite1,suite2,suite3")
    required: true
  environment-id:
    description: environment id
    required: true
  environment-url:
    description: environment url
    required: false
  github-comment:
    description:
      If enabled, the action will comment on the pull request with the test run
      results
    default: 'true'
  github-token:
    description: This token used for leaving a comment on the pull request
    default: ${{ github.token }}
  async:
    description: |
      If enabled, will launch the tests but not wait for them to finish and the action will always output success.
      Note: GitHub comments will not function if this is set.
    default: 'false'
  commit-sha:
    description: 'The commit SHA to find the pull request for comment'
    required: false
  timeout-seconds:
    description: 'Maximum time to wait for test runs to complete (in seconds)'
    required: false
    default: '86400'

# Define your outputs here.
outputs:
  success:
    description: Whether all test runs were successful
  results:
    description: JSON string containing results for each test suite

runs:
  using: node20
  main: dist/index.js
