import { context, getOctokit } from '@actions/github'
import { TestRun, TestRunResult } from '../client/entity.js'

const resultEmoji = {
  Pending: '🔄',
  Passed: '✅',
  Failed: '❌',
  Skipped: '⏭️'
}

export interface Config {
  token: string
}

export interface CommentConfig {
  testSuiteID: string
  testSuiteName: string
  testSuiteRun: TestRun
}

export class Github {
  private config: Config
  private core: ReturnType<typeof getOctokit>

  constructor(config: Config) {
    this.config = config

    this.core = getOctokit(config.token)
  }

  async comment(config: CommentConfig) {
    const commentIdentifier = `<!-- loggia_${config.testSuiteID} -->`

    const testSuiteURL = `https://app.loggia.ai/test-suites/${config.testSuiteID}`
    const testSuiteRunResultURL = `https://app.loggia.ai/run-results/${config.testSuiteRun?.id}`

    const body = `${commentIdentifier}
# [Loggia](https://app.loggia.ai) Runner

| Name | Result | Start Time | End Time |
| :--- | :----- | :------ | :------ |
| **[${config.testSuiteName})(${testSuiteURL})** | ${resultEmoji[config.testSuiteRun?.result]} ${config.testSuiteRun?.result} ([Inspect](${testSuiteRunResultURL})) | ${config.testSuiteRun.startTime || '-'} | ${config.testSuiteRun.endTime || '-'} |

---
_This comment was automatically generated by [Loggia GitHub Action](https://github.com/marketplace/actions/loggia-action)_
`

    // check if the comment already exists
    const comments = await this.core.rest.issues.listComments({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.payload.pull_request!.number
    })
    const commit = comments.data.find((comment) =>
      comment.body?.startsWith(commentIdentifier)
    )
    if (commit?.id) {
      // update the comment
      await this.core.rest.issues.updateComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        comment_id: commit.id,
        body
      })
    } else {
      // create a new comment
      await this.core.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: context.payload.pull_request!.number,
        body
      })
    }
  }
}
