name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main
      - master

permissions: write-all

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      # - name: Test
      #   id: npm-ci-test
      #   run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          api-token: ${{ secrets.LOGGIA_API_TOKEN }}
          test-suite-id: ${{ secrets.LOGGIA_TEST_SUITE_ID }}
          environment-id: ${{ secrets.LOGGIA_ENVIRONMENT_ID }}
          environment-url: ${{ secrets.LOGGIA_TEST_SUITE_ENVIRONMENT_URL }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
